### PR TITLE
[feat] add specific environment configuration

### PR DESCRIPTION
**Pull request by richard-infai**
see issue #5

### CODE REVIEW

**Comment by tempuser5432** [comment]
+1 for fallback values

**Comment by tempuser5432** [comment]
Closes #5

**Comment by richard-infai** [comment]
After this changes, see conflict: 
@tempuser5432 Should i add this properties also as env variables?

* auth-signature-service.endpointAddress
* auth-signature-service.smbcCardHandle
* card-service.endpointAddress
* idp.connector.cert.auth.store.file
* idp.connector.cert.auth.store.file.password
* idp.connector.auth-signature.endpoint.address
/wip

**Comment by tempuser5432** [comment]
The cardhandle is the same value for all corresponding keys.

The `idp.connector.auth.store.file` should remain a fixed value.

The different endpoint addresses should be configurable by a `CONNECTOR_ADDRESS` env (e.g. `https://10.0.0.2:443`) that will be used in the relevant config keys, e.g.
```
signature-service.endpointAddress=${CONNECTOR_ADDRESS}/ws/SignatureService
```
allthough, I am uncertain whether the `/ws/SignatureService` is constant for all connectors. @ManuelB please check

**Comment by ManuelB** [comment]
@tempuser5432 the URL is *not* consistent. As far as I know all connectors offer an connector.sds file. This file contains the URLs to the services:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:ConnectorServices
    xmlns="http://ws.gematik.de/int/version/ProductInformation/v1.1"
    xmlns:ns2="http://ws.gematik.de/conn/ServiceDirectory/v3.1"
    xmlns:ns3="http://ws.gematik.de/conn/ServiceInformation/v2.0">
    <ProductInformation>
        <InformationDate>2021-06-17T06:29:40.808Z</InformationDate>
        <ProductTypeInformation>
            <ProductType>Konnektor PTV4</ProductType>
            <ProductTypeVersion>4.8.2</ProductTypeVersion>
        </ProductTypeInformation>
        <ProductIdentification>
            <ProductVendorID>SECUN</ProductVendorID>
            <ProductCode>secu_kon</ProductCode>
            <ProductVersion>
                <Local>
                    <HWVersion>2.0.0</HWVersion>
                    <FWVersion>4.1.3</FWVersion>
                </Local>
            </ProductVersion>
        </ProductIdentification>
        <ProductMiscellaneous>
            <ProductVendorName>secunet Security Networks AG</ProductVendorName>
            <ProductName>secunet konnektor 2.0.0</ProductName>
        </ProductMiscellaneous>
    </ProductInformation>
    <ns2:TLSMandatory>true</ns2:TLSMandatory>
    <ns2:ClientAutMandatory>true</ns2:ClientAutMandatory>
    <ns3:ServiceInformation>
        <ns3:Service Name="EncryptionService">
            <ns3:Abstract>Der Verschlüsselungsdienst bietet Schnittstellen zum hybriden und symmetrischen Ver- und Entschlüsseln von Dokumenten an.</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/EncryptionService/WSDL/v6.1" Version="6.1.1">
                    <ns3:Abstract>Der Verschlüsselungsdienst bietet Schnittstellen zum hybriden und symmetrischen Ver- und Entschlüsseln von Dokumenten an.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/EncryptionService"/>
                </ns3:Version>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/EncryptionService/WSDL/v6.1" Version="6.1.0">
                    <ns3:Abstract>Der Verschlüsselungsdienst bietet Schnittstellen zum hybriden und symmetrischen Ver- und Entschlüsseln von Dokumenten an.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/EncryptionService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="SignatureService">
            <ns3:Abstract>Der Signaturdienst bietet Clientsystemen und Fachmodulen eine Schnittstelle zum Signieren von Dokumenten und Prüfen von Dokumentensignaturen</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/SignatureService/WSDL/v7.4" Version="7.4.2">
                    <ns3:Abstract>Der Signaturdienst bietet Clientsystemen und Fachmodulen eine Schnittstelle zum Signieren von Dokumenten und Prüfen von Dokumentensignaturen</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/SignatureService"/>
                </ns3:Version>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/SignatureService/WSDL/v7.4" Version="7.4.0">
                    <ns3:Abstract>Der Signaturdienst bietet Clientsystemen und Fachmodulen eine Schnittstelle zum Signieren von Dokumenten und Prüfen von Dokumentensignaturen</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/SignatureService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="AuthSignatureService">
            <ns3:Abstract>Der Authentifizierungsdienst bietet Clientsystemen und Fachmodulen eine Schnittstelle zum Signieren von Binärstrings zum Zweck der externen Authentisierung.</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/AuthSignatureService/WSDL/v7.4" Version="7.4.1">
                    <ns3:Abstract>Der Authentifizierungsdienst bietet Clientsystemen und Fachmodulen eine Schnittstelle zum Signieren von Binärstrings zum Zweck der externen Authentisierung.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/AuthSignatureService"/>
                </ns3:Version>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/AuthSignatureService/WSDL/v7.4" Version="7.4.0">
                    <ns3:Abstract>Der Authentifizierungsdienst bietet Clientsystemen und Fachmodulen eine Schnittstelle zum Signieren von Binärstrings zum Zweck der externen Authentisierung.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/AuthSignatureService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="CardService">
            <ns3:Abstract>Der Konnektor verwaltet eine Liste aller Karten (CM_CARD_LIST), die in die vom Konnektor verwalteten Kartenterminals gesteckt sind (CTM_CT_LIST). Alle Ereignisse und Operationen, die sich auf Karten beziehen, werden durch diesen Basisdienst gekapselt.</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/CardService/WSDL/v8.1" Version="8.1.2">
                    <ns3:Abstract>Der Konnektor verwaltet eine Liste aller Karten (CM_CARD_LIST), die in die vom Konnektor verwalteten Kartenterminals gesteckt sind (CTM_CT_LIST). Alle Ereignisse und Operationen, die sich auf Karten beziehen, werden durch diesen Basisdienst gekapselt.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/CardService"/>
                </ns3:Version>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/CardService/WSDL/v8.1" Version="8.1.1">
                    <ns3:Abstract>Der Konnektor verwaltet eine Liste aller Karten (CM_CARD_LIST), die in die vom Konnektor verwalteten Kartenterminals gesteckt sind (CTM_CT_LIST). Alle Ereignisse und Operationen, die sich auf Karten beziehen, werden durch diesen Basisdienst gekapselt.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/CardService"/>
                </ns3:Version>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/CardService/WSDL/v8.1" Version="8.1.0">
                    <ns3:Abstract>Der Konnektor verwaltet eine Liste aller Karten (CM_CARD_LIST), die in die vom Konnektor verwalteten Kartenterminals gesteckt sind (CTM_CT_LIST). Alle Ereignisse und Operationen, die sich auf Karten beziehen, werden durch diesen Basisdienst gekapselt.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/CardService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="EventService">
            <ns3:Abstract>Der Systeminformationsdienst stellt Basisdiensten, Fachmodulen und Clientsystemen sowohl aktiv (Push-Mechanismus) wie passiv (Pull-Mechanismus) Informationen zur Verfügung. Dabei erhebt er selbst keine Daten, sondern dient nur als zentraler Mechanismus, der von anderen Basisdiensten und Fachmodulen zur Verteilung und Bereitstellung derer Informationen verwendet werden kann.</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/EventService/WSDL/v7.2" Version="7.2.0">
                    <ns3:Abstract>Der Systeminformationsdienst stellt Basisdiensten, Fachmodulen und Clientsystemen sowohl aktiv (Push-Mechanismus) wie passiv (Pull-Mechanismus) Informationen zur Verfügung. Dabei erhebt er selbst keine Daten, sondern dient nur als zentraler Mechanismus, der von anderen Basisdiensten und Fachmodulen zur Verteilung und Bereitstellung derer Informationen verwendet werden kann.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/EventService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="CertificateService">
            <ns3:Abstract>Der Zertifikatsdienst bietet eine Schnittstelle zur Überprüfung der Gültigkeit von Zertifikaten an. Dies geschieht auf Grundlage des durch den Vertrauensanker TSL-CA-SignerZertifikat und eine aktuelle, gültige TSL aufgespannten Vertrauensraums sowie unter Berücksichtigung von aktuellen Statusinformationen (OCSP, CRL). Die Zertifikatsprüfung wird sowohl für nonQES- als auch für QES-Zertifikate unterstützt.</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/CertificateService/WSDL/v6.0" Version="6.0.1">
                    <ns3:Abstract>Der Zertifikatsdienst bietet eine Schnittstelle zur Überprüfung der Gültigkeit von Zertifikaten an. Dies geschieht auf Grundlage des durch den Vertrauensanker TSL-CA-SignerZertifikat und eine aktuelle, gültige TSL aufgespannten Vertrauensraums sowie unter Berücksichtigung von aktuellen Statusinformationen (OCSP, CRL). Die Zertifikatsprüfung wird sowohl für nonQES- als auch für QES-Zertifikate unterstützt.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/CertificateService"/>
                </ns3:Version>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/CertificateService/WSDL/v6.0" Version="6.0.0">
                    <ns3:Abstract>Der Zertifikatsdienst bietet eine Schnittstelle zur Überprüfung der Gültigkeit von Zertifikaten an. Dies geschieht auf Grundlage des durch den Vertrauensanker TSL-CA-SignerZertifikat und eine aktuelle, gültige TSL aufgespannten Vertrauensraums sowie unter Berücksichtigung von aktuellen Statusinformationen (OCSP, CRL). Die Zertifikatsprüfung wird sowohl für nonQES- als auch für QES-Zertifikate unterstützt.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/CertificateService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="CardTerminalService">
            <ns3:Abstract>Die Aufgabe des Kartenterminaldienstes ist das Management aller vom Konnektor adressierbaren Kartenterminals. Dies umfasst alle administrativen Prozesse. Ferner kapselt der Kartenterminaldienst die Zugriffe auf Kartenterminals durch Basisdienste und Fachmodule.</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/CardTerminalService/WSDL/v1.1" Version="1.1.0">
                    <ns3:Abstract>Die Aufgabe des Kartenterminaldienstes ist das Management aller vom Konnektor adressierbaren Kartenterminals. Dies umfasst alle administrativen Prozesse. Ferner kapselt der Kartenterminaldienst die Zugriffe auf Kartenterminals durch Basisdienste und Fachmodule.</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/CardTerminalService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="VSDService">
            <ns3:Abstract>VSD von eGK lesen</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/vsds/VSDService/v5.2" Version="5.2.0">
                    <ns3:Abstract>VSD von eGK lesen</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/VSDService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
        <ns3:Service Name="KVKService">
            <ns3:Abstract>Versichertendaten von KVK lesen</ns3:Abstract>
            <ns3:Versions>
                <ns3:Version TargetNamespace="http://ws.gematik.de/conn/vsds/KvkService/v4.0" Version="4.0.0">
                    <ns3:Abstract>Versichertendaten von KVK lesen</ns3:Abstract>
                    <ns3:EndpointTLS Location="https://10.0.0.98:443/ws/KVKService"/>
                </ns3:Version>
            </ns3:Versions>
        </ns3:Service>
    </ns3:ServiceInformation>
</ns2:ConnectorServices>
```

**Comment by tempuser5432** [comment]
So the correct way would be to specify the connector address and then autodiscover the other service urls.
@richard-infai this means, for this issue, all endpoint addresses need to be specified in different variables.

**Pull request merged**
